export default {
  LOGIN: "Login",
  SIGNUP: "Signup",
  PREF: "Preferences",
  HOME: "Home",
  HOME_NEW_POST: "HomeNewPost",
  PROFILE: "Perfil",
  EDIT_PROFILE: "EditProfile",
  TABS: "Tabs",
  FORO: "Foro",
  GAMEFORO: "GAMEFORO",
  FORUMPOST: "FORUMPOST",
  CHATPLUSHOME: "ChatplusHOME",
  CHAT: "Chat",
  CHATPLUS: "Chatplus",
  CHATPLUSPROFILE: "ChatplusProfile",
  ADDGAMES: "AddGames",
  MATCHCHATS: "MatchChats",
  FRIENDSREQUEST: "FriendsRequest",
  NOTIFICATIONS: "Notificaciones",
  POSTDETAILS: "PostDetails",
  SHOWIMAGE: "ShowImage",
  COMENTS: "Coments",
  EXTERNALUSERPROFILE: "ExternalUserProfile",
  DEFAULT: "Default",
};
